import os
from typing import List, Optional

DOCKERFILE_TEMPLATE = """\
# Generated by MCP Arena
FROM python:3.11-slim-bookworm

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    git \\
    curl \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies
RUN pip install --upgrade pip

# Install mcp-arena
RUN pip install mcp-arena[all]

# Install additional requirements if present
COPY requirements.txt .
RUN if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

# Copy application code
COPY . .

# Create a non-root user
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

# Expose port (default for many MCP servers)
EXPOSE 8000

# Default command
ENTRYPOINT ["python", "main.py"]
"""

DOCKER_COMPOSE_TEMPLATE = """\
version: '3.8'

services:
  mcp-agent:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MCP_LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    restart: unless-stopped
"""

def generate_dockerfile(output_dir: str = ".") -> str:
    """
    Generate a Dockerfile in the specified directory.
    
    Args:
        output_dir: Directory where Dockerfile should be created
        
    Returns:
        Path to the created Dockerfile
    """
    file_path = os.path.join(output_dir, "Dockerfile")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(DOCKERFILE_TEMPLATE)
    return file_path

def generate_docker_compose(output_dir: str = ".") -> str:
    """
    Generate a docker-compose.yml file.
    
    Args:
        output_dir: Directory where docker-compose.yml should be created
    
    Returns:
        Path to the created docker-compose.yml
    """
    file_path = os.path.join(output_dir, "docker-compose.yml")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(DOCKER_COMPOSE_TEMPLATE)
    return file_path
